version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run: sudo apt install -y rsync
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "ed:8d:d2:52:a9:91:f5:3e:73:6f:39:c9:57:5a:53:fb"
      - run:
          name: Deploy Over SSH
          command: |
            printf "export RESPOND_TO_DM=\"$RESPOND_TO_DM\"\n\
            export RESPOND_TO_LIVECHAT=\"$RESPOND_TO_LIVECHAT\"\n\
            export ROCKETCHAT_URL=\"$ROCKETCHAT_URL\"\n\
            export ROCKETCHAT_PASSWORD=\"$ROCKETCHAT_PASSWORD\"\n\
            export ROCKETCHAT_ROOM=\"$ROCKETCHAT_ROOM\"\n\
            export ROCKETCHAT_USER=\"$ROCKETCHAT_USER\"\n\
            export ROCKETCHAT_USESSL=\"$ROCKETCHAT_USESSL\"\n" > .env
            rsync -avce "ssh -o StrictHostKeyChecking=no" ~/repo/ $SSH_USER@$SSH_HOST:/root/marvin
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /root/marvin/ && \
            ./start.sh &"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master